### ISSUE TITLE
General Question - What is this for?

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/wordpress-docker#34]
Is this container used in a tutorial, or is there any other documentation outside the README's?

What is its intended use?

**Comment by bshaffer** [comment]
Asking because we can add it to https://cloud.google.com/wordpress/ if we have some instructions on its intended use. Currently we are linking to [this Wordpress on kubernetes](https://cloud.google.com/kubernetes-engine/docs/tutorials/persistent-disk) tutorial.

**Comment by deustis** [comment]
Hi Brent, this image was developed for distribution on Cloud Launcher:
console.cloud.google.com/launcher/details/google/wordpress4-php7-apache
